Added Moving Traps with 4 Slime Types
9hack/aldente pull request #132
Opened 2017-05-26 10:11 UTC by AustinPuk

Major Changes:
- Added a "MobileTrap" base class for movable traps.
- Added a base "Trap" class that all traps inherit from. 
- Changed how client update is handled, giving a specific c_update call
- All game objects have update_state() called, except for tiles.

Minor Changes:
- Added a bunch of Slime assets
- Reset function for game objects that is called in beginning of build phase
- Player can pick up objects when invulnerable, stun length is longer though.
- Essence amount gained is only lost in multiples of 10. 

Needs Work:
- Yeah, the way Grid has a huge case statement for Constructs is ugly.

2017-05-26 20:17 UTC, jytang commented on src/game_objects/construct.cpp
> +    initial_z = z;
make a copy of the transform (initial_transform)

2017-05-27 10:25 UTC, AznCelebration approved these changes

2017-05-27 10:32 UTC, richard1 requested changes
Couple small things but LGTM

:goberserk:

2017-05-27 10:32 UTC, richard1 commented on src/ui/ui_manager.cpp
> +        int num_available_constructs = 7; // Need better way than hardcoding this number
🎉  `Constructs::CONSTRUCTS.size();`

2017-05-27 10:32 UTC, richard1 commented on src/game/construct_types.h
> +	    { ConstructType::SLIME_B, { ConstructType::SLIME_B, 10, "Blue Slime", "Likes to loop", "slime_blue.png" } },
Seems to be a tab here

2017-05-27 10:32 UTC, richard1 commented on src/net/network_manager.cpp
> +#include "game_objects/traps/slime.h"
Unneeded include?

2017-05-27 10:47 UTC, merged