My name is Austin "Refactor" Puk
9hack/aldente pull request #18
Opened 2017-04-21 02:43 UTC by jytang

"don't worry about Keyboard for now, it kind of needs attention"

2017-04-21 03:37 UTC, metakirby5 commented
Thanks for the hard work! Richard and I will look at this tomorrow afternoon together.

2017-04-21 03:39 UTC, metakirby5 commented
(Also, if you have time, please fix the merge conflict. It's a tiny one because I redid the events (again). This is the last time, since I found a boost thing that does it well 😆 )

2017-04-21 03:42 UTC, metakirby5 commented
One more thing: I just tried compiling & running, and I got this output:

```
Compiling vertex shader: basic/vert.glsl
Compiling fragment shader: basic/frag.glsl
Compiled and linked shader: basic
Compiling vertex shader: skybox/vert.glsl
Compiling fragment shader: skybox/frag.glsl
Compiled and linked shader: skybox
Compiling vertex shader: shadow/vert.glsl
Compiling fragment shader: shadow/frag.glsl
Compiled and linked shader: shadow
Compiling vertex shader: debug_shadow/vert.glsl
Compiling fragment shader: debug_shadow/frag.glsl
Compiled and linked shader: debug_shadow
Compiling vertex shader: debug_pink/vert.glsl
Compiling fragment shader: debug_pink/frag.glsl
WARNING: Output of vertex shader 'frag_normal' not read by fragment shader
WARNING: Output of vertex shader 'frag_poa s' not read by fragment shader
WARNING: Output of vertex shader 'frag_pos_light' not read by fragment shader
WARNING: Output of vertex shader 'frag_tex_coord' not read by fragment shader

Compiled and linked shader: debug_pink
```

This was followed by a black screen. Any idea what might be going on?

2017-04-22 01:51 UTC, richard1 requested changes
Made a quick first pass, would like to discuss some of the proposed design changes if possible

2017-04-22 01:51 UTC, richard1 commented on shaders/basic/frag.glsl
> +        tex_color = vec3(texture(texture_map, frag_tex_coord));
Please be consistent about tabs vs. spaces (not just here, throughout the commit)

2017-04-22 01:51 UTC, richard1 commented on src/aldente.cpp
>  Aldente::~Aldente() {}
Can remove constructor and destructor since they're just their respective defaults

2017-04-22 01:51 UTC, richard1 commented on src/aldente.h
> +	static Aldente* aldente;
Is there a reason why this class has a static instance of itself?

2017-04-22 01:51 UTC, richard1 commented on src/asset_loader.cpp
> +AssetLoader::~AssetLoader() {}
Default constructor/destructor, so don't need to have these

2017-04-22 01:51 UTC, richard1 commented on src/asset_loader.cpp
> +		Material *loadMat = new Material();
Memory for `loadMat` not freed (memory leak)

2017-04-22 01:51 UTC, richard1 commented on src/asset_loader.cpp
> +		final_mesh = new Mesh(geo, loadMat, ShaderManager::get_default());
Is this memory actually freed anywhere?

2017-04-22 01:51 UTC, richard1 commented on src/asset_loader.cpp
> +		final_mesh = new Mesh(geo, blank, ShaderManager::get_default());
`Mesh` doesn't seem to be freeing memory of `blank` (memory leak)

2017-04-22 01:51 UTC, richard1 commented on src/main.cpp
> +	Aldente::aldente->go();
What's the motivation of ditching the local objects for these static pointers?  It makes it much harder to manage our memory...

2017-04-22 01:51 UTC, richard1 commented on src/scene/scene_camera.cpp
> +}
This constructor does nothing with the shader.  Intentional?

2017-04-22 01:51 UTC, richard1 commented on src/shaders/shader.cpp
> +	if (b)
Should add comment on what `b` is

2017-04-22 01:51 UTC, richard1 commented on src/shadows.cpp
> +	if (Aldente::aldente->shadows_on)
I think I see why we're using Aldente as a global static instance... if it's for config stuff like this, I think it's better to have some static config class you can include.  As it is, `#include "aldente.h"` can potentially lead to a circular dependency down the line

2017-04-22 01:51 UTC, richard1 commented on src/window.cpp
> +Window *Window::window = new Window();
Another static instance

2017-04-22 03:14 UTC, metakirby5 requested changes
Not done yet, have to go for dinner. But PLEASE ditch the global pointer design pattern. Use dependency injection by reference and stack allocation.

2017-04-22 03:14 UTC, metakirby5 commented on src/aldente.cpp
> +Aldente* Aldente::aldente = new Aldente();
Any reason why this is a pointer? Why not just `Aldente::aldente = Aldente()`

2017-04-22 03:14 UTC, metakirby5 commented on src/grid.h
>  using namespace std;
Don't do this. Always refer to things by `std::`.

2017-04-22 03:14 UTC, metakirby5 commented on src/model/mesh.h
>  using namespace std;
Don't do this. Always refer to things by `std::`.

2017-04-22 03:14 UTC, metakirby5 commented on src/aldente.cpp
> +    main_scene = new MainScene();
Can we maybe get a `SceneManager` for scene-related work?

2017-04-22 03:14 UTC, metakirby5 commented on src/aldente.cpp
> +	Physics::physics->setup_bullet();
Not a huge fan of the "static pointer" design philosophy. Can we perhaps instantiate these modules on the stack and inject dependencies by reference? For example, if a `Physics p` needs an `AssetLoader a`, construct it as `Phsyics p(a)`.

2017-04-22 03:14 UTC, metakirby5 commented on src/aldente.h
> +	std::vector<Scene *> get_scenes(); // Gets list of all scenes in the game
`SceneManager`?

2017-04-22 03:14 UTC, metakirby5 commented on src/aldente.h
> +	void go();	// Main Game Loop
Maybe name more descriptively, like `start_game_loop`?

2017-04-22 03:14 UTC, metakirby5 commented on src/aldente.h
> +	bool shadows_on = true;
Let's have a global `Flags` module to control system-wide flags?

2017-04-22 03:14 UTC, metakirby5 commented on src/asset_loader.cpp
> +#include "asset_loader.h"
Regarding the filename: are we doing always underscores?

2017-04-22 03:14 UTC, metakirby5 commented on src/asset_loader.cpp
> +		Material *loadMat = new Material();
Unless there's a reason to allocate on the heap, just do it on the staack.

2017-04-22 03:14 UTC, metakirby5 commented on src/asset_loader.cpp
> +		Material *blank = new Material(color::white);
Allocate on stack?

2017-04-22 03:14 UTC, metakirby5 commented on src/game_object.cpp
> +	this->scene = scene;
Extraneous use of `this`.

2017-04-22 03:14 UTC, metakirby5 commented on src/game_object.cpp
> +	this->model = m;
Extraneous use of `this`.

2017-04-22 03:14 UTC, metakirby5 commented on src/game_object.cpp
> +	if (model)
Is every `GameObject` guaranteed to have a model? If so, why not just pass it in through the constructor?

2017-04-22 03:14 UTC, metakirby5 commented on src/game_object.h
> +class GameObject :
Put inheritance on same line.

Also, at the moment, this seems to be a thin wrapper over `Model`. I assume you're going to add more things to this, though.

2017-04-22 03:14 UTC, metakirby5 commented on src/keyboard.cpp
> +// TODO : This class won't be used in the final game anyways.
However, it will be useful for debugging when we don't have controllers readily available. Good to keep this around.

2017-04-22 03:14 UTC, metakirby5 commented on src/keyboard.cpp
> +const GLfloat BASE_CAM_SPEED = 0.1f;
Please qualify with static if these are not meant to be globally visible.

Also, we should separate input logic from camera logic. Consider a separate `Camera` module, and we can lump in keyboard and mouse stuff into our existing gamepad-handling `input` module.

2017-04-22 03:14 UTC, metakirby5 commented on src/keyboard.h
> +	Handles GLFW calls for getting Mouse and Keyboard Input
Inaccurate - it handles calls for getting input AND manipulation of the camera in response to the input. Please decouple.

2017-04-22 04:09 UTC, AznCelebration commented on src/asset_loader.h
> +	AssetLoader();
What's the reasoning for making the assetLoader constructor private and having a static pointer to an instance?

2017-04-22 04:11 UTC, AznCelebration commented on src/asset_loader.h
> +	AssetLoader();
What's the reasoning for making the constructor private and adding a pointer?

2017-04-22 04:14 UTC, AznCelebration commented on src/asset_loader.h
> +	AssetLoader();
What's the reasoning for making the constructor private?

2017-04-22 05:22 UTC, metakirby5 requested changes
Feeling kinda meh about this bracket on newline convention...

Also NO MORE SINGLETONS PLEASE

2017-04-22 05:22 UTC, metakirby5 commented on src/model/geometry_generator.cpp
> +    if (has_texture != 0)
Redundant `!= 0`

2017-04-22 05:22 UTC, metakirby5 commented on src/model/material.cpp
> +	this->ambient = color;
Redundant use of `this->`

2017-04-22 05:22 UTC, metakirby5 commented on src/model/material.cpp
> +	ambient = { 0.f, 0.f, 0.f };
Consider using default arguments instead of a separate constructor, since this just sets defaults.

2017-04-22 05:22 UTC, metakirby5 commented on src/model/material.cpp
> +Material::~Material()
Not necessary.

2017-04-22 05:22 UTC, metakirby5 commented on src/model/mesh.cpp
> +	this->shader = ShaderManager::get_default();
STOP USING THIS GOD DAMMIT

2017-04-22 05:22 UTC, metakirby5 commented on src/model/mesh.cpp
> +Mesh::Mesh(Geometry *geo, Material *mat)
USE DEFAULT ARGS

2017-04-22 05:22 UTC, metakirby5 commented on src/model/mesh.h
> +    // map<string, Anim*> animations();
What is this

2017-04-22 05:22 UTC, metakirby5 commented on src/model/model.cpp
> +Model::Model(Scene *scene)
DEFAULT ARGS FOR CONSTRUCTORS

2017-04-22 05:22 UTC, metakirby5 commented on src/model/model.cpp
> +            mega_geometry->normals.push_back(glm::normalize(glm::mat3(glm::transpose(glm::inverse(mesh->to_world))) * n));
Please split this on multiple lines...

2017-04-22 05:22 UTC, metakirby5 commented on src/physics.cpp
> +Physics *Physics::physics = new Physics();
Reminder about global static pointers. Please use dependency injection and stack allocation.

2017-04-22 05:22 UTC, metakirby5 commented on src/physics.cpp
> +	broadphase = new btDbvtBroadphase();
Reminder heap > stack. Also, why is this not just a constructor?

2017-04-22 05:22 UTC, metakirby5 commented on src/asset_loader.h
> +	AssetLoader();
What are your reasons for the singleton pattern?

2017-04-22 05:22 UTC, metakirby5 commented on src/asset_loader.cpp
> +void AssetLoader::setup()
This should just be the constructor. Again, not sure of the reason for the singleton pattern.

2017-04-22 05:22 UTC, metakirby5 commented on src/physics.h
> +	static Physics *physics; // Singleton
please stop

2017-04-22 05:22 UTC, metakirby5 commented on src/scene/scene.cpp
> +    camera = new SceneCamera(this);
Whitespace

2017-04-22 05:22 UTC, metakirby5 commented on src/scene/scene.cpp
> +    camera = new SceneCamera(this);
Also reminder: only put on heap if necessary

2017-04-22 05:22 UTC, metakirby5 commented on src/scene/scene_camera.h
> +	glm::mat4 P;
Could use more descriptive variable names here.

2017-04-22 05:22 UTC, metakirby5 commented on src/setup.cpp
> +	glfwSetErrorCallback(Window::error_callback);
This is kinda gross... Can't we have each class be responsible for setting its own callback?

2017-04-22 05:22 UTC, metakirby5 commented on src/shaders/basic_shader.cpp
> +void BasicShader::set_material(Material *m)
Use a const reference?

2017-04-22 05:22 UTC, metakirby5 commented on src/shaders/shader.cpp
> +	else
Braces please

2017-04-22 05:22 UTC, metakirby5 commented on src/shaders/shader.cpp
> +void Shader::set_material(Material *m) {}
What is this?

2017-04-22 05:22 UTC, metakirby5 commented on src/shaders/skybox_shader.cpp
> +void SkyboxShader::set_material(Material *m)
What are all these empty methods for?

2017-04-22 05:22 UTC, metakirby5 commented on src/shadows.cpp
> +	if (Aldente::aldente->shadows_on)
Global flags class?

2017-04-22 05:22 UTC, metakirby5 commented on src/shadows.h
> +	static Shadows *shadows;
pls no sinegltone

2017-04-22 05:22 UTC, metakirby5 commented on src/window.cpp
> +Window *Window::window = new Window();
![](https://i.imgflip.com/1noq4y.jpg)

2017-04-22 05:22 UTC, metakirby5 commented on src/window.cpp
> +void Window::poll_events()
Seems like unnecessary indirection. Polling events does not belong to a window exclusively.

2017-04-22 05:22 UTC, metakirby5 commented on src/window.cpp
> +int Window::should_close(GLFWwindow *window)
What's the point of a class if you just keep passing in pointers? Make window a private variable and use that...

2017-04-22 05:22 UTC, metakirby5 commented
Nobody touch this, I'll work on it.

2017-04-23 09:26 UTC, metakirby5 commented
Closing because we have another PR open for this.

2017-04-23 09:26 UTC, closed without merging