Protobufs
9hack/aldente pull request #21
Opened 2017-04-23 08:29 UTC by richard1

Adds capability to send protocol buffer messages between server/clients through our existing Boost networking setup.

### Notes
- Need to compile `.proto` files with protobuf **version 2.6**, since that's the highest available version in NuGet.  Shouldn't be too much of a problem since we're not missing any critical features of proto3.
- `aldente.cpp` contains some example code that demonstrates the functionality, for your reviewing convenience.

### WIP
- Remove `message.{h, cpp}` and move this logic into `Connection`

2017-04-24 21:10 UTC, richard1 commented on src/net/network_server.cpp
>              messages[c.first].push_back(message);
TODO: need to serialize?

2017-04-24 21:10 UTC, richard1 commented on src/net/network_server.cpp
> +void NetworkServer::send_to_all(google::protobuf::Message& message) {
Add newline before

2017-04-24 21:10 UTC, richard1 commented on src/net/network_server.cpp
>              messages[c.first].push_back(message);
TODO: deserialize

2017-04-24 21:11 UTC, richard1 commented on src/net/network_server.cpp
> +        while ((message = c.second->read_message()).length() > 0) {
Should be returning vector of Messages

2017-04-24 22:45 UTC, metakirby5 reviewed
Excellent job fam. Question: how do we detect what kind of message we actually have in a `google::protobuf::Message`? I can't imagine putting `dynamic_cast<GameObject>(message)` at all receive sites to be too friendly. A few possible solutions include:

- Templating `read_message` on a message type and taking care of dynamic casting there, caching the read as a static function variable and returning false if type mismatch. This creates a network bottleneck if a lot of systems need message B but message A is next to be read and no one is reading it. We may be able to work around it with clever templating and a FIFO queue per message type.
- Have only one message type, and just stick a bunch of optional fields in it.
- Introduce the notion of "endpoints" and maintain separate typed queues per endpoint.

I like the idea of endpoints, but working out a demuxing strategy might be challenging.

2017-04-24 22:45 UTC, metakirby5 commented on src/aldente.cpp
> +                kuuhaku::proto::GameObject msg;
I think most of us gave up on the `kuuhaku` top-level namespace, so we can just use a `proto` namespace.

2017-04-24 22:45 UTC, metakirby5 commented on src/net/connection.cpp
> +    rcvbuf.resize(HEADER_SIZE + length);
Is there a reason why we must keep the header? Why not `rcvbuf.resize(length)`, then pass in `rcvbuf` to the buffer constructor, don't add `HEADER_SIZE` to the start of body, etc.?

2017-04-24 22:45 UTC, metakirby5 commented on src/net/connection.cpp
> +uint32_t Connection::decode_header(const std::vector<uint8_t>& buf) {
Use pointers to indicate output parameter.

Also, good job on dealing with endian-ness (not that it will be an issue in the demo, but it's good to have).

2017-04-24 22:45 UTC, metakirby5 commented on src/net/connection.cpp
> +    for (int i = 0; i < msg_size; i++) {
Could use `strncpy` here maybe?

2017-04-24 22:45 UTC, metakirby5 commented on src/net/connection.h
> +#include <assert.h>
I don't think the assert import is required.

2017-04-24 23:45 UTC, richard1 commented
@metakirby5 that's a good question.  I think this depends on whether or not we're comfortable with using one message format that both the server and client sends/receives.  While this is doable, I think this will end up being too cluttered.

My proposal is to have one message that the client must always receive, and a different message that the server must always receive.  We can then template the client's `read_message` and the server's `read_all_message`.  I think this is a good tradeoff between messiness of message types and allowing reading messages to be dynamic.

Thoughts?  I'll push a commit with these proposed changes in a bit.

2017-04-25 01:37 UTC, metakirby5 commented
@richard1 This seems reasonable, but if we're fixing receivable message types, why bother templating at all? We can just define a ServerMessage and ClientMessage proto and fill it out as we go.

2017-04-25 01:42 UTC, richard1 commented
@metakirby5 that makes sense, so something along these lines?

Server
- `send(ServerMessage)`
- `ClientMessage read()`

Client
- `send(ClientMessage)`
- `ServerMessage read()`

I'm okay with this approach - I'll go ahead and draft this up if you agree.

2017-04-25 02:20 UTC, metakirby5 commented
@richard1 Small change: keep the bool success / input parameter stye in (e.g. `bool read(ServerMessage *read_to)`). Other than that, sounds good.

2017-04-26 01:39 UTC, metakirby5 requested changes
LGTM, just address these minor points and you can go ahead and merge

2017-04-26 01:39 UTC, metakirby5 commented on src/proto/net.proto
> +  required int32 id = 1;
`required` considered harmful, use `optional` (default in proto3)

2017-04-26 01:39 UTC, metakirby5 commented on src/proto/net.proto
> +  required string message = 1;
May as well swap out for the `oneof` thing we discussed

2017-04-26 01:39 UTC, metakirby5 commented on src/proto/net.proto
>  package kuuhaku.proto;
Since we're not really using `kuuhaku` namespace, maybe just do `package proto`?

2017-04-26 05:46 UTC, richard1 commented
Merging per @metakirby5's request

2017-04-26 05:46 UTC, merged