Compatibility with animations
9hack/aldente pull request #41
Opened 2017-05-01 09:30 UTC by AustinPuk

(Stealing Joshua's template)
# Main Changes
- Asset loader now loads all animations on initialization and attaches them to its respective model.
- Changed asset directory such that models and animations are separated (note, an fbx can only hold one animation. Format for naming models is "model_name.fbx", and format for animations will be "model_name@animation_name.fbx").
- Added an Animation Player that can can be attached to a game object to play a model's animation. ``player.play(mode, "anim_name");``
- Created an Animation class in which animations are stored. However, due to the complexity of actually recreating Assimp's node structure and keyframe structure, I ended up just saving Assimp's node structure instead and using their node structure to actually calculate and play animations.  
- Added a "skeleton" to the model. Models now hold all of its own bone information (initialized to just identity matrices when not used).
- Calculations for bone transformations are done in the shader, and therefore information regarding the bone weights and indices were also added to the ``Geometry`` class.
- Added an "unlit" shader so that we can have the option for models to not be affected by lighting. 

# Miscellaneous Changes
- Gave shaders a ``set_uni`` helper function for making setting uniforms more simple. 
- Created a walking animation for the boy, ``boy_two.fbx``, but had to make a new rig for it, therefore it cannot use the same .fbx as ``boy.fbx``.

# TODO for future
- There is a small bug where the mesh's local matrix is being multiplied twice when using the animation player due to how the bone transformations are calculated. Currently it is hardcoded to cancel the second multiplied matrix using its inverse, but I need to look into it more to understand exactly what the matrix multiplication is doing and maybe find a better solution.
- Animation player currently uses its own timer that it keeps track itself. We may move towards a more event based timer in the future. 
- This still needs to be tested with more complicated models and more complicated animations (e.g. models that are made up of a lot of meshes).

2017-05-01 18:35 UTC, richard1 reviewed
Looks good to me on first glance - nice work.  Only comment I have is to remove tabs (since some places you have mixed tabs & spaces).  Since this is graphics-heavy I'll defer to @AznCelebration and @jytang.

2017-05-02 04:50 UTC, jytang requested changes
Looks good overall. Like Richard commented, may want to be consistent with tabs and spaces or it may incite some annoyance.

2017-05-02 04:50 UTC, jytang commented on src/model/geometry.cpp
> +    glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(GLuint) * indices.size(), indices.data(), GL_STATIC_DRAW);
Duplicate of above (line 45-48), please fix.

2017-05-02 04:50 UTC, jytang commented on src/game_object.cpp
> +        */
Please make a derived class (like PlayerModel) and override ``GameObject::update`` with it.

2017-05-02 04:50 UTC, jytang commented on src/animation/animation_player.cpp
> +    assert(0);
Comment these assertions. Why does the code never reach these lines?

2017-05-02 05:03 UTC, AustinPuk commented on src/model/geometry.cpp
> +    glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(GLuint) * indices.size(), indices.data(), GL_STATIC_DRAW);
了解

2017-05-02 05:03 UTC, AustinPuk commented on src/game_object.cpp
> +        */
了解

2017-05-02 05:03 UTC, AustinPuk commented on src/animation/animation_player.cpp
> +    assert(0);
了解

2017-05-02 07:21 UTC, AznCelebration approved these changes

2017-05-02 07:55 UTC, jytang approved these changes
:ship: it

2017-05-02 21:11 UTC, merged