Added proper camera controls to phases
9hack/aldente pull request #59
Opened 2017-05-06 19:30 UTC by AustinPuk

# Main Changes
- Made camera follow player during Dungeon Phase.
- Can now use the right joystick (arrow keys) to pan camera during Build Phase, while using the left joystick (wasd) to move the selection. 
- Made debug_input with keyboard and mouse toggle-able with the 'V' button

# Miscellaneous Changes
- Removed 'Z' and 'X' for selecting and deselecting on build phase, since the button mapping in Debug.h already handles that using 'H' and 'J'. 
- Cleaned up debug_input.cpp a little bit by removing unnecessary stuff and separating movement functions.
- Added events for signaling the start and end of the build phase.

# TODO for future
- Debug input is still messy, but I wasn't planning on really polishing it anytime soon.
- Need to eventually make a better API for manipulating the camera's transform
- SceneCamera should be renamed to Camera
- Currently the "panning" movement for the Build Phase is very choppy, since we need some sort of continuous event for the joysticks rather than discreet ones.

2017-05-06 19:31 UTC, AustinPuk commented on src/game/phase.cpp
> +    events::build::end_build_event();
Is this the right place to put this?

2017-05-06 19:32 UTC, AustinPuk commented on src/game_objects/grid.cpp
> +    if (grid[hoverZ][hoverX] != hover) {
Due to the nature of the way I import the map data, the grid uses [row][column], so it actually works more like [z][x]. Sorry for any confusion. I'll need to figure out a cleaner way to make sure ppl don't get confused

2017-05-07 03:05 UTC, AznCelebration commented on src/game_objects/player.cpp
> +    events::dungeon::player_position_event(transform.get_position());
Changing the event name to indicate that you're sending the position would be better. That way we know that it is getting the player position, not setting it.

2017-05-07 06:39 UTC, metakirby5 requested changes
Everything looks quite nice and clean, excellent job 😄
🚢 whenever ready

2017-05-07 06:39 UTC, metakirby5 commented on src/debug_input.cpp
>      events::window_mouse_button_event.connect([&](events::WindowMouseButtonData d) {
Should probably just get rid of the entire `connect` if we don't need it. Ditto for the `window_scroll_event` one.

2017-05-07 06:39 UTC, metakirby5 commented on src/events.h
> +        extern signal<void(StickData)> pan_camera_event;
Maybe `StickData` is a bit overkill, would just a `std::pair<int, int>` work?

2017-05-07 06:39 UTC, metakirby5 commented on src/game/phase.cpp
> +    events::build::end_build_event();
Pinging @richard1

2017-05-07 06:39 UTC, metakirby5 commented on src/game_objects/grid.cpp
> +    if (grid[hoverZ][hoverX] != hover) {
I think just a comment to note stuff (like you already have) is fine.

2017-05-07 06:39 UTC, metakirby5 commented on src/game_objects/player.cpp
> +    events::dungeon::player_position_event(transform.get_position());
Agreed; maybe call it `player_position_updated_event`?

2017-05-07 10:16 UTC, richard1 commented on src/game/phase.cpp
> +    events::build::end_build_event();
Sure, it's okay for now.  Later on, the server would determine when build phase ends, and should broadcast a message indicating that it has ended.

2017-05-07 10:16 UTC, richard1 approved these changes

2017-05-07 10:57 UTC, merged