AudioManager
9hack/aldente pull request #81
Opened 2017-05-16 02:44 UTC by dminlee02

Created AudioManager and music_events to play music. I have the basic functionality of playing different (for now 10 seconds, looped) songs for the build and dungeon phases.
For AudioData, I might add future variables for volume, looped, etc. so we can have more fine-grain control for both the music and sound effects.

2017-05-16 04:25 UTC, AznCelebration commented on src/events.h
> +    };
Are u planning to have other variables in this struct? If not, then just the string would be fine

2017-05-16 05:01 UTC, richard1 reviewed
Minor comments, but looks good overall.  Good job!

2017-05-16 05:01 UTC, richard1 commented on src/audio/audio_manager.cpp
> +        {
Curly brace on previous line pls

2017-05-16 05:01 UTC, richard1 commented on src/audio/audio_manager.cpp
> +            fprintf(stderr, "AudioManager: Cannot open %s\n", filename);
Can use `std::cerr` instead for consistency

2017-05-16 07:02 UTC, Pukami approved these changes
Worked fine on my computer, and I don't see any problems.

2017-05-16 07:33 UTC, jytang commented on src/events.h
> +    };
or a typedef, either way

2017-05-16 07:34 UTC, jytang commented on src/events.h
> +    };
wait, he said this in the pr description: "For AudioData, I might add future variables for volume, looped, etc. so we can have more fine-grain control for both the music and sound effects."

2017-05-16 07:36 UTC, jytang approved these changes
Looks good. For the future, as for sound effects and such like (latency sensitive), we may want to load audio assets into memory at startup.

2017-05-16 20:17 UTC, metakirby5 requested changes
Please add the following line to the Makefile, for us non-VS users:

```make
LIBS            += -lsfml-system -lsfml-audio
```

Other than that and the fprintf thing, looks good and works on my machine.
 🚢

2017-05-16 20:17 UTC, metakirby5 commented on src/audio/audio_manager.cpp
> +            fprintf(stderr, "AudioManager: Cannot open %s\n", filename);
This also does not compile with `clang++`, you need to use `filename.c_str()` if you want to use fprintf. Or just use `std::cerr`.

2017-05-18 20:50 UTC, richard1 approved these changes
I added a commit (which adds a space).  LGTM

2017-05-19 22:31 UTC, merged